### ISSUE TITLE
Error with Eslint being out of date

### ISSUE THREAD

**Issue by BenMcLoughlin** [telus/eslint-config#26]
I'm updating my packages and keep getting this error: 
<img width="458" alt="Screenshot 2023-03-30 at 9 25 02 AM" src="https://user-images.githubusercontent.com/45271003/228902044-661bcb09-9e1c-48c1-8457-818207be6d3a.png">

I suppose I should just keep the eslint as the earlier version in my package.json but it would be nice to be able to update it if we want.

**Comment by kyletsang** [comment]
Will be releasing a new version shortly that's not super outdated
